server:
  port: 9011

spring:
  application:
    name: mars-auth
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/star_system?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
